export const GET_POKEMONS_URL = 'GET_POKEMONS_URL';
export const GET_POKEMONS = 'GET_POKEMONS';
export const GET_SINGLE_POKEMON = 'GET_SINGLE_POKEMON';
export const SET_LOADING = 'SET_LOADING';
export const GET_EVOLUTIONS = 'GET_EVOLUTIONS';
